#!/bin/bash

#use curl to fetch data from the api, jq to stream it in json format

POKEMON_API_URL="https://pokeapi.co/api/v2/"
OUTPUT_FILE="data.json"
ERROR_FILE="error.txt"

response=$(curl -s -w "%{http_code}" "$URL")

#takes the last three characters of the response
status_code=${response: -3}

#removes the last 3 characters from the response and assigns them to the body
body_response=${response%???}

if [ "$status_code" -eq 200 ]; then
	echo "$body_response" > "$OUTPUT_FILE"
	echo "Data saved to $OUTPUT_FILE"
else
	echo "$(date '+%Y-%m-%d %H:%M:%S') - Error fetching data. HTTP status: $status_code" >> "$ERROR_FILE"
fi
