#!/bin/bash

#script that fetches pokemon data faster by leveraging parallel processing

#an array of pokemons
pokemon_list=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")

for pokemon in "${pokemon_list[@]}"; do
	echo "Fetching data for $pokemon in background..."
	file_name="pokemon_data/${pokemon}.json"

	#running curl in the background using &
	curl -s -o "$file_name" "https://pokeapi.co/api/v2/pokemon/${pokemon}" &	sleep 1
done

echo "All fetch processes started. Waiting for them to finish..."

# Wait for ALL background processes to finish
wait

echo "All data fetched successfully!"
