#!/bin/bash

#script that fetches the names of the requested pokemon and outputs it in a readable format

#get the name and use sed to capitalise the first letter
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')

#get the height and convert it to kg using awk, with 0 dp
HEIGHT=$(jq '.height' data.json)
formatted_weight=$(awk 'printf{"%.1f", $1/10}')

#get the weight and convert it to m using awk, with 0 dp
weight=$(jq '.weight' data.json)
formatted_weight=$(awk 'printf{"%.0f", $1/10}')

#get the type and use sed to capitalise the first letter
type=$(jq -r 'types[0].type.name' data.json | sed 's/.*/\u$/')

#the output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.}"
