#!/bin/bash

#script to read json files from batchProcessing-0x02 amd extract the name, height and weight of each pokemon

#> overwrites, >> appends
echo "Name,Height (m),Weight (kg)" > "pokemon_report.csv"

#loop through each file
for file in pokemon_data/*.json; do
	name=$(jq -r '.name' "$file" | sed 's/.*/\u&/')
	height=$(jq '.height / 10' "$file" | sed 's/.*/\u&/')
	weight=$(jq '.weight / 10' "$file" | sed 's/.*/\u&/')

	echo "$name,$height,$weight" >> "pokemon_report.csv"
done

#calculating the average height. -F sets the field separator as comma
#NR>1 excludes the header, and NR-1 is all the lines minus the first one
awk -F, 'NR>1 { sum_height +=$2} END {printf("Average Height: %.1f m\n", sum_height/(NR-1))' "pokemon_report.csv"

#calculating the avaerage weight
awk -F, 'NR>1 { sum_weight += $3} END {printf("Average Weight: %.1f kg\n", sum_weight/(NR-1))}' "pokemon_report.csv"
