#!/bin/bash

#pokemon url
POKEMON_URL="https://pokeapi.co/api/v2/pokemon/"

#takes the last three characters
RESPONSE_STATUS=${response: -3}

#takes the rest of the response except the last three
RESPONSE_BODY=${response%???}

if ["$RESPONSE_STATUS" -eq 200]
	echo "$RESPONSE_BODY" > data.json
	echo "Data saved to data.json"
else
	echo "$(date '+%Y-%m-%d %H:%M:%S' - Error fetching data; HTTP status:$RESPONSE_STATUS)" >> "error.txt"
fi
